name: exe2dist
description: Binary executable packaging tool.
version: 0.1.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  archive: ^3.3.1

dependencies:
  args: ^2.3.1
  either_dart: ^0.2.0
  path: ^1.8.2
