name: exe2dist
description: Binary executable packaging tool.
version: 0.3.3

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  archive: ^3.3.1
  glob: ^2.1.0
  path: ^1.8.2

